In [29]:
import pandas as pd
import matplotlib.pyplot as plt, numpy as np, math as m

In [30]:
df = pd.read_excel('./OLX_Car_Data.xlsx')
df.head(100)

,Brand,Condition,Fuel,KMs_Driven,Model,Price,Registered_City,Transaction_Type,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,Karachi,Cash,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,Karachi,Cash,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000,Karachi,Cash,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000,Karachi,Cash,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000,Karachi,Cash,2013.0
5,Toyota,Used,Petrol,80000.0,Corrolla Altis,1620000,Karachi,Cash,2012.0
6,Suzuki,New,CNG,65000.0,Cultus VXL,450000,Karachi,Cash,2006.0
7,Toyota,New,Petrol,10241.0,Corrolla Altis,2900000,Karachi,Cash,2017.0
8,Suzuki,Used,CNG,83000.0,Alto,490000,Karachi,Cash,2009.0
9,Honda,Used,Petrol,1.0,Civic VTi,480000,Karachi,Cash,1997.0
10,Suzuki,Used,CNG,123.0,Khyber,230000,Karachi,Cash,1994.0
11,Suzuki,Used,CNG,73000.0,Liana,535000,Karachi,Cash,2006.0
12,Toyota,Used,Petrol,78000.0,Passo,770000,Karachi,Cash,2006.0
13,Honda,Used,Petrol,1.0,Civic Prosmetic,490000,Karachi,Cash,1997.0
14,Honda,Used,CNG,170000.0,Civic EXi,160000,Karachi,Cash,1984.0
15,Suzuki,Used,Petrol,200000.0,Alto,425000,Karachi,Cash,2005.0
16,Daihatsu,Used,Petrol,100000.0,Charade,180000,Karachi,Cash,1988.0
17,Mitsubishi,Used,Petrol,82000.0,Pajero Mini,520000,Karachi,Cash,1995.0
18,Suzuki,Used,CNG,10000.0,Margalla,400000,Karachi,Cash,1990.0
19,Honda,Used,Petrol,69500.0,City IVTEC,1400000,Karachi,Cash,2014.0
20,Suzuki,Used,CNG,10000.0,Khyber,175000,Karachi,Cash,1989.0
21,KIA,Used,CNG,123456.0,Classic,120000,Karachi,Cash,2001.0
22,Honda,Used,CNG,87611.0,Civic EXi,590000,Karachi,Cash,2000.0
23,Honda,Used,Hybrid,19000.0,Other,425000,Karachi,Cash,1995.0
24,Honda,Used,CNG,99000.0,Civic EXi,685000,Karachi,Cash,2005.0
25,Suzuki,Used,CNG,88000.0,Alto,465000,Karachi,Cash,2007.0
26,Toyota,Used,Petrol,75000.0,Corolla GLI,1190000,Karachi,Cash,2010.0
27,Other Brands,Used,Petrol,124000.0,Other,850000,Karachi,Cash,2010.0
28,Suzuki,Used,CNG,76000.0,Cultus VXR,370000,Karachi,Cash,2002.0
29,Nissan,New,Petrol,47000.0,Dayz Highway Star,1175000,Karachi,Cash,2013.0
...,...,...,...,...,...,...,...,...,...
70,Suzuki,Used,CNG,17000.0,Mehran VX,110000,Hyderabad,Cash,1991.0
71,Honda,Used,Petrol,100000.0,City IDSI,765000,Karachi,Cash,2004.0
72,Toyota,Used,Petrol,130000.0,Premio,1150000,Karachi,Cash,2003.0
73,Suzuki,Used,Petrol,150000.0,Alto,410000,Karachi,Cash,2007.0
74,Suzuki,Used,CNG,17000.0,Mehran VX,110000,Hyderabad,Cash,1991.0
75,Honda,Used,Petrol,100000.0,City IDSI,765000,Karachi,Cash,2004.0
76,Toyota,Used,Petrol,130000.0,Premio,1150000,Karachi,Cash,2003.0
77,Suzuki,Used,Petrol,150000.0,Alto,410000,Karachi,Cash,2007.0
78,Toyota,Used,Petrol,55000.0,Corolla GLI,1890000,Karachi,Cash,2016.0
79,Suzuki,Used,Petrol,70000.0,Cultus VXR,790000,Karachi,Cash,2011.0
80,Daihatsu,Used,Petrol,102000.0,Mira,785000,Karachi,Cash,2011.0
81,Suzuki,Used,Petrol,1700000.0,Mehran VX,270000,Karachi,Cash,2006.0
82,Toyota,Used,CNG,100000.0,Sprinter,150000,Karachi,Cash,1987.0
83,BMW,Used,CNG,53524.0,3 Series,550000,Karachi,Cash,1997.0
84,Mazda,Used,Petrol,78000.0,Other,825000,Karachi,Cash,2007.0
85,Toyota,Used,Diesel,40000.0,Hilux,3850000,Karachi,Cash,2013.0
86,Suzuki,Used,Petrol,90000.0,Mehran VXR,490000,Karachi,Cash,2012.0
87,Toyota,Used,Petrol,40000.0,Vitz,1250000,Karachi,Cash,2010.0
88,Daihatsu,Used,Petrol,80000.0,Charade,135000,Karachi,Cash,1986.0
89,Mitsubishi,New,Petrol,96000.0,Lancer,780000,Karachi,Cash,2008.0
90,Other Brands,Used,Diesel,38000.0,Other,4500000,Karachi,Cash,2012.0
91,Suzuki,Used,Petrol,83000.0,Alto,430000,Karachi,Cash,2006.0
92,Honda,New,Petrol,10900.0,Civic VTi Oriel Prosmatec,2880000,Karachi,Cash,2017.0
93,Toyota,Used,Petrol,64600.0,Passo,975000,Karachi,Cash,2007.0
94,Suzuki,Used,Petrol,80000.0,Cultus VXR,440000,Karachi,Cash,2004.0
95,Suzuki,Used,CNG,85000.0,Cultus VXR,440000,Karachi,Cash,2007.0
96,Suzuki,Used,CNG,52000.0,Mehran VXR,400000,Karachi,Cash,2008.0
97,Suzuki,Used,CNG,1.0,Bolan,305000,Karachi,Cash,1997.0
98,Suzuki,Used,Petrol,48000.0,Mehran VX,450000,Karachi,Cash,2012.0
99,Suzuki,Used,Petrol,50000.0,Swift,1140000,Karachi,Cash,2015.0

In [33]:
df.describe()

         KMs_Driven         Price          Year
count  2.268700e+04  2.497300e+04  22689.000000
mean   1.278112e+05  9.128953e+05   2005.901626
std    5.996726e+05  1.537134e+06      9.563804
min    1.000000e+00  5.000000e+04   1915.000000
25%    1.600000e+04  3.800000e+05   2002.000000
50%    6.651000e+04  6.500000e+05   2008.000000
75%    1.000000e+05  1.145000e+06   2013.000000
max    1.000000e+07  8.765432e+07   2020.000000

In [31]:
newdf=df.dropna(how='all')
newdf.head(50)

,Brand,Condition,Fuel,KMs_Driven,Model,Price,Registered_City,Transaction_Type,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,Karachi,Cash,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,Karachi,Cash,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000,Karachi,Cash,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000,Karachi,Cash,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000,Karachi,Cash,2013.0
5,Toyota,Used,Petrol,80000.0,Corrolla Altis,1620000,Karachi,Cash,2012.0
6,Suzuki,New,CNG,65000.0,Cultus VXL,450000,Karachi,Cash,2006.0
7,Toyota,New,Petrol,10241.0,Corrolla Altis,2900000,Karachi,Cash,2017.0
8,Suzuki,Used,CNG,83000.0,Alto,490000,Karachi,Cash,2009.0
9,Honda,Used,Petrol,1.0,Civic VTi,480000,Karachi,Cash,1997.0
10,Suzuki,Used,CNG,123.0,Khyber,230000,Karachi,Cash,1994.0
11,Suzuki,Used,CNG,73000.0,Liana,535000,Karachi,Cash,2006.0
12,Toyota,Used,Petrol,78000.0,Passo,770000,Karachi,Cash,2006.0
13,Honda,Used,Petrol,1.0,Civic Prosmetic,490000,Karachi,Cash,1997.0
14,Honda,Used,CNG,170000.0,Civic EXi,160000,Karachi,Cash,1984.0
15,Suzuki,Used,Petrol,200000.0,Alto,425000,Karachi,Cash,2005.0
16,Daihatsu,Used,Petrol,100000.0,Charade,180000,Karachi,Cash,1988.0
17,Mitsubishi,Used,Petrol,82000.0,Pajero Mini,520000,Karachi,Cash,1995.0
18,Suzuki,Used,CNG,10000.0,Margalla,400000,Karachi,Cash,1990.0
19,Honda,Used,Petrol,69500.0,City IVTEC,1400000,Karachi,Cash,2014.0
20,Suzuki,Used,CNG,10000.0,Khyber,175000,Karachi,Cash,1989.0
21,KIA,Used,CNG,123456.0,Classic,120000,Karachi,Cash,2001.0
22,Honda,Used,CNG,87611.0,Civic EXi,590000,Karachi,Cash,2000.0
23,Honda,Used,Hybrid,19000.0,Other,425000,Karachi,Cash,1995.0
24,Honda,Used,CNG,99000.0,Civic EXi,685000,Karachi,Cash,2005.0
25,Suzuki,Used,CNG,88000.0,Alto,465000,Karachi,Cash,2007.0
26,Toyota,Used,Petrol,75000.0,Corolla GLI,1190000,Karachi,Cash,2010.0
27,Other Brands,Used,Petrol,124000.0,Other,850000,Karachi,Cash,2010.0
28,Suzuki,Used,CNG,76000.0,Cultus VXR,370000,Karachi,Cash,2002.0
29,Nissan,New,Petrol,47000.0,Dayz Highway Star,1175000,Karachi,Cash,2013.0
30,Toyota,New,Petrol,43000.0,Corolla XLI,1675000,Karachi,Cash,2015.0
31,Suzuki,Used,CNG,3875.0,Mehran VX,195000,Karachi,Cash,1999.0
32,Suzuki,Used,CNG,98000.0,Mehran VX,165000,Karachi,Cash,1991.0
33,Suzuki,Used,Petrol,1000.0,Alto,420000,Karachi,Cash,2006.0
34,Toyota,Used,Petrol,39000.0,Vitz,1430000,Karachi,Cash,2014.0
35,Suzuki,Used,CNG,127000.0,Mehran VXR,150000,Karachi,Cash,1991.0
36,Suzuki,Used,LPG,786.0,Carry,130000,Karachi,Cash,1982.0
37,Suzuki,Used,CNG,70.0,Cultus VXR,415000,Karachi,Cash,2004.0
38,Suzuki,Used,CNG,99999.0,Mehran VX,185000,Karachi,Cash,1997.0
39,Toyota,Used,Petrol,89000.0,Passo,1040000,Karachi,Cash,2010.0
40,Suzuki,Used,CNG,1.0,Cultus VX,400000,Karachi,Cash,2002.0
41,Suzuki,Used,Petrol,100000.0,Cultus VXR,360000,Karachi,Cash,2001.0
42,Toyota,New,Petrol,69000.0,Vitz,1150000,Karachi,Cash,2003.0
43,Suzuki,New,CNG,65000.0,Mehran VX,265000,Karachi,Cash,2005.0
44,Suzuki,New,CNG,73000.0,Mehran VXR,435000,Karachi,Cash,2009.0
45,Toyota,Used,Petrol,163000.0,Corolla GLI,1220000,Karachi,Cash,2009.0
46,Suzuki,Used,CNG,56.0,Cultus VXR,780000,Karachi,Cash,2011.0
47,Suzuki,Used,CNG,10000.0,Bolan,250000,Karachi,Cash,1987.0
48,Toyota,Used,Petrol,190.0,Corrolla Altis,875000,Karachi,Cash,2004.0
49,Toyota,Used,CNG,65000.0,Corolla XLI,1260000,Karachi,Cash,2013.0

In [32]:
columns = ['Registered_City','Transaction_Type']
df.drop(columns, inplace=True, axis=1)
df

,Brand,Condition,Fuel,KMs_Driven,Model,Price,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000,2013.0
5,Toyota,Used,Petrol,80000.0,Corrolla Altis,1620000,2012.0
6,Suzuki,New,CNG,65000.0,Cultus VXL,450000,2006.0
7,Toyota,New,Petrol,10241.0,Corrolla Altis,2900000,2017.0
8,Suzuki,Used,CNG,83000.0,Alto,490000,2009.0
9,Honda,Used,Petrol,1.0,Civic VTi,480000,1997.0
10,Suzuki,Used,CNG,123.0,Khyber,230000,1994.0
11,Suzuki,Used,CNG,73000.0,Liana,535000,2006.0
12,Toyota,Used,Petrol,78000.0,Passo,770000,2006.0
13,Honda,Used,Petrol,1.0,Civic Prosmetic,490000,1997.0
14,Honda,Used,CNG,170000.0,Civic EXi,160000,1984.0
15,Suzuki,Used,Petrol,200000.0,Alto,425000,2005.0
16,Daihatsu,Used,Petrol,100000.0,Charade,180000,1988.0
17,Mitsubishi,Used,Petrol,82000.0,Pajero Mini,520000,1995.0
18,Suzuki,Used,CNG,10000.0,Margalla,400000,1990.0
19,Honda,Used,Petrol,69500.0,City IVTEC,1400000,2014.0
20,Suzuki,Used,CNG,10000.0,Khyber,175000,1989.0
21,KIA,Used,CNG,123456.0,Classic,120000,2001.0
22,Honda,Used,CNG,87611.0,Civic EXi,590000,2000.0
23,Honda,Used,Hybrid,19000.0,Other,425000,1995.0
24,Honda,Used,CNG,99000.0,Civic EXi,685000,2005.0
25,Suzuki,Used,CNG,88000.0,Alto,465000,2007.0
26,Toyota,Used,Petrol,75000.0,Corolla GLI,1190000,2010.0
27,Other Brands,Used,Petrol,124000.0,Other,850000,2010.0
28,Suzuki,Used,CNG,76000.0,Cultus VXR,370000,2002.0
29,Nissan,New,Petrol,47000.0,Dayz Highway Star,1175000,2013.0
...,...,...,...,...,...,...,...
24943,Daihatsu,Used,Petrol,52451.0,Cuore,480000,2003.0
24944,Suzuki,Used,Petrol,25000.0,Cultus VXR,475000,2004.0
24945,Honda,Used,CNG,100000.0,BR-V,229000,1995.0
24946,Toyota,New,Petrol,19000.0,Corolla XLI,1890000,2017.0
24947,Suzuki,Used,Petrol,24000.0,Alto,1150000,2011.0
24948,NaN,NaN,NaN,NaN,NaN,595000,NaN
24949,NaN,NaN,NaN,NaN,NaN,266000,NaN
24950,Classic & Antiques,Used,Diesel,12354.0,Other,349000,1979.0
24951,Suzuki,Used,Petrol,120000.0,Mehran VX,510000,2012.0
24952,Hyundai,Used,CNG,80000.0,Excel,310000,1993.0
24953,Suzuki,Used,Petrol,99999.0,Cultus VXR,490000,2006.0
24954,Suzuki,Used,CNG,978345.0,Alto,435000,2003.0
24955,Nissan,New,Petrol,170000.0,March,730000,2003.0
24956,Suzuki,Used,Petrol,29008.0,Ravi,650000,2011.0
24957,Suzuki,Used,Petrol,111111.0,Every Wagon,880000,2014.0
24958,Toyota,New,Petrol,104000.0,Corolla GLI,1290000,2011.0
24959,Daihatsu,Used,Petrol,30000.0,Move,240000,2014.0
24960,Honda,Used,Petrol,25000.0,Civic VTi Oriel Prosmatec,3100000,2017.0
24961,Suzuki,Used,CNG,999999.0,Cultus VXR,380000,2001.0
24962,Toyota,Used,Petrol,200000.0,Vitz,725000,1999.0
24963,Toyota,Used,Petrol,56686.0,Fj Cruiser,165000,1971.0
24964,Suzuki,Used,CNG,100000.0,Mehran VX,230000,1989.0
24965,Toyota,Used,CNG,100000.0,Corolla XE,520000,1994.0
24966,Toyota,Used,Petrol,76190.0,Avanza,1175000,2011.0
24967,NaN,NaN,NaN,NaN,NaN,1175000,NaN
24968,Toyota,Used,CNG,200000.0,Corolla XE,1070000,2001.0
24969,Daihatsu,New,Petrol,10000.0,Cuore,390000,2004.0
24970,Other Brands,Used,CNG,158715.0,Other,180000,2000.0
24971,Suzuki,Used,Petrol,1.0,Alto,470000,2003.0
24972,Toyota,Used,Petrol,48500.0,Corolla GLI,2050000,2017.0

In [38]:
new_df=df.dropna()
new_df

ValueError: No axis named Year for object type <class 'type'>

In [36]:
df.Year.isnull().sum()

2284

In [37]:
df.KMs_Driven = df.KMs_Driven.apply(int)
print(df)

ValueError: cannot convert float NaN to integer

In [26]:
df.Year = df.Year.apply(int)
print(df)

ValueError: cannot convert float NaN to integer